version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel/app
    container_name: sgpe_app
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www:delegated
      - ./docker_config_files/php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
      - ~/.composer/docker-cache/:/root/.composer:cached
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: sgpe_webserver
    tty: true
    ports:
      - "85:80"
      - "445:443"
    volumes:
      - ./:/var/www:delegated
      - ./docker_config_files/nginx/conf.d/:/etc/nginx/conf.d/:delegated
    networks:
      - app-network
    depends_on:
      - app

  #Postgres Service
  postgres:
    container_name: sgpe_postgres
    image: postgres
    environment:
      POSTGRES_USER: upgest
      POSTGRES_PASSWORD: upgest
      PGDATA: /data/postgres
    volumes:
      - ./upgest:/data/postgres:delegated
    ports:
      - "5435:5432"
    networks:
      - app-network

  #composer
  composer:
    image: composer:latest
    container_name: sgpe_composer
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    depends_on:
      - app
    networks:
      - app-network

  #npm
  npm:
    image: node:13.7
    container_name: sgpe_npm
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    entrypoint: ['npm']

  #artisan
  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sgpe_artisan
    volumes:
      - ./:/var/www
    working_dir: /var/www/
    entrypoint: ['php', '/var/www/artisan']
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
